export interface LicenseData {
    id: number;
    licenseNumber: string;
    licenseType: string;
    issuingDate: string;
    expiryDate: string;
    status: string;
    issuingAuthority: string;
    companyName: string;
    processedBy: string;
    companyId: number;
    wpcStreetAddress: string;
    wpcAddressLine2: string;
    wpcPin: string;
    wpcCity: string;
    wpcDistrict: string;
    wpcState: string;
    wpcCountry: string;
    contactPersonId: number;
    contactPersonName: string;
    contactPersonNumber: string;
    contactPersonEmailId: string;
    geographicalCoverage: string;
    endUsePurpose: string;
    licenseDocumentUrl: string | null;
    etaCertificateUrl: string | null;
    importLicenseUrl: string | null;
    otherDocumentsUrls: string[];
    createdBy: string;
    lastUpdatedBy: string | null;
    createdAt: string;
    updatedAt: string;
    customer: {
      id: number;
      name: string;
      website: string;
      ancillaryName: string;
      typeOfCustomer: string;
      companyName: string;
      email: string;
      phone: string;
      industry: string;
      gstNumber: string;
      images: string[];
      userId: string;
      createdAt: string;
      updatedAt: string;
    };
    devices: {
      id: number;
      licenseId: number;
      productName: string;
      brand: string;
      frequencyRange: string;
      powerOutput: number;
      quantityApproved: number;
      countryOfOrigin: string;
      equipmentType: string;
      technologyUsed: string;
      createdAt: string;
      updatedAt: string;
    }[];
  }