import { LicenseType } from "../../../types/LicenseType";
import { OrderItem, OrderTotals } from "./OrderItems";

export default interface OrderFormData {
    id?: number;
    orderNumber: string;
    orderName: string;
    executiveName: string;
    orderDate: string;
    orderCreationDate: string;
    orderStatus: string;
    customerId?: number;
    customerName?: string;
    customerGST: string;
    customerEmail: string;
    customerPhone: string;
    pocId?: number;
    pocName?: string;
    pocEmail: string;
    pocPhone: string;
    pocDesignation: string;
    pocDepartment: string;
    billingAddress: string;
    shippingAddress: string;
    wpcAddress: string;
    paymentTerm: string;
    deliveryInstruction: string;
    modeOfDispatch: string;
    warranty: string;
    orderRemarks: string;
    requiresLicense: boolean;
    licenseType?: LicenseType;
    licenseNumber?: string;
    licenseExpiryDate?: string;
    licenseIssueDate?: string;
    licenseQuantity?: string;
    liaisoningRemarks?: string;
    liaisoningVerified: boolean;
    liquidatedDamagesInclusive: boolean;
    liquidatedDamagesAmount: number;
    freightChargeInclusive: boolean;
    freightChargeAmount: number;
    transitInsuranceInclusive: boolean;
    transitInsuranceAmount: number;
    installationInclusive: boolean;
    installationAmount: number;
    securityDepositInclusive: boolean;
    securityDepositAmount: number;
    liaisoningInclusive: boolean;
    liaisoningAmount: number;
    documents: File[];
    performanceBankGuarantee: File | null;
    items: OrderItem[];
    subtotal?: number;
    taxAmount?: number;
    discountAmount?: number;
    totalAmount?: number;
    additionalCostTotal?: number;
    grandTotal?: number;
    orderTotals?: OrderTotals;
  }
