import { CustomerOption } from "./OrderOptionTypes";
import { POCOption } from "./OrderOptionTypes";
import { OrderItem, OrderTotals } from "./OrderItems";
import { LicenseType } from "../../../types/LicenseType";

export default interface OrderFormState {
    orderNumber: string;
    orderName: string;
    executiveName: string;
    orderCreationDate: string;
    orderDate: string;
    orderStatus: string;
    customers: CustomerOption[];
    selectedCustomer: CustomerOption | null;
    customerGST: string;
    customerEmail: string;
    customerPhone: string;
    billingAddress: string;
    shippingAddress: string;
    wpcAddress: string;
    poc: POCOption[];
    selectedPoc: POCOption | null;
    pocEmail: string;
    pocPhone: string;
    pocDesignation: string;
    pocDepartment: string;
    paymentTerm: string;
    deliveryInstruction: string;
    modeOfDispatch: string;
    warranty: string;
    orderRemarks: string;
    requiresLicense: boolean;
    licenseType: LicenseType;
    licenseNumber: string;
    licenseIssueDate: string;
    licenseExpiryDate: string;
    licenseQuantity: string;
    liaisoningRemarks: string;
    liaisoningVerified: boolean;
    liquidatedDamagesInclusive: boolean;
    liquidatedDamagesAmount: number;
    freightChargeInclusive: boolean;
    freightChargeAmount: number;
    transitInsuranceInclusive: boolean;
    transitInsuranceAmount: number;
    installationInclusive: boolean;
    installationAmount: number;
    securityDepositInclusive: boolean;
    securityDepositAmount: number;
    liaisoningInclusive: boolean;
    liaisoningAmount: number;
    documents: File[];
    performanceBankGuarantee: File | null;
    orderItems: OrderItem[];
    orderTotals: OrderTotals;
    activeTab: string;
    isSubmitting: boolean;
    isGeneratingOrderNumber: boolean;
}
